# Generated by Django 2.2.4 on 2021-02-13 17:15

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('SOUND', 'Sound Designer'), ('CODE', 'Software Engineer'), ('MUSIC', 'Musician'), ('VIDEO', 'Videographer')], default='CODE', max_length=100)),
                ('primary_image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=250)),
                ('summary', tinymce.models.HTMLField(blank=True, max_length=1000)),
                ('detail', tinymce.models.HTMLField(blank=True, max_length=100000)),
                ('template', models.TextField(blank=True, max_length=100)),
            ],
        ),
    ]
