# Generated by Django 2.2.4 on 2021-04-14 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20210414_0049'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectTypes',
            new_name='ProjectType',
        ),
    ]
